#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the hourglassSum function below.
""" 
a b c
  d
e f g
"""
def hourglassSum(arr):
    
    result = -sys.maxsize
    for i in range(1,len(arr)-1):
        for j in range(1,len(arr[0])-1):
            s = arr[i-1][j-1]+arr[i-1][j]+arr[i-1][j+1]+arr[i][j]+arr[i+1][j-1]+arr[i+1][j]+arr[i+1][j+1]
            result = max(s,result)
    
    return result

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))

    result = hourglassSum(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
