#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the acmTeam function below.
def acmTeam(topic):
    largest = 0
    teams = {}
    for i in range(n):
        for j in range(i+1,n):
            count = 0
            for k in range(m):
                if topic[i][k] == '1' or topic[j][k] == '1':
                    count += 1
            if count >= largest:
                largest = count
                teams[count] = teams.get(count,0)+1
    return [largest,teams[largest]]

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    topic = []

    for _ in range(n):
        topic_item = input()
        topic.append(topic_item)

    result = acmTeam(topic)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
