#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the appendAndDelete function below.
def appendAndDelete(s, t, k):

    if len(s)+len(t) <= k:
        return 'Yes'

    i,j = 0,0
    while i < len(s) and j < len(t) and s[i]==t[j]:
        i += 1
        j += 1
    if i == len(s) and s and len(t)-j < k and (k-(len(t)-j))%2 != 0:
        return 'No'
    op = len(s)-i+len(t)-j
    return 'Yes' if op <= k else 'No'
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    t = input()

    k = int(input())

    result = appendAndDelete(s, t, k)

    fptr.write(result + '\n')

    fptr.close()
