#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the arrayManipulation function below.
def arrayManipulation(n, queries):
    d = {}
    for q in queries:
        d[q[0]-1] = d.get(q[0]-1,0)+q[2]
        d[q[1]] = d.get(q[1],0)- q[2]
    start = d.get(0,0)
    ans = d.get(0,0)
    for i in range(1,n):
        start = d.get(i,0)+start
        ans = max(ans,start)
    return ans

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    queries = []

    for _ in range(m):
        queries.append(list(map(int, input().rstrip().split())))

    result = arrayManipulation(n, queries)

    fptr.write(str(result) + '\n')

    fptr.close()
