#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the flatlandSpaceStations function below.
def flatlandSpaceStations(n, c):

    maxDistance = -sys.maxsize
    # sort the list as the space stations are unordered
    c.sort()
    #loop for checking all the cases except the first and last space stations
    for i in range(1,len(c)):
        maxDistance = max(maxDistance,(c[i]-c[i-1])//2)
    # Edge cases
    #To check the distance of first and last city from first and last space station 
    maxDistance = max(maxDistance,c[0], n-1-c[-1])
    return maxDistance

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    c = list(map(int, input().rstrip().split()))

    result = flatlandSpaceStations(n, c)

    fptr.write(str(result) + '\n')

    fptr.close()
