#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the minimumBribes function below.
def minimumBribes(q):
    
    moves = 0
    for i in range(n):
        if q[i]> i+1+2:
            print( 'Too chaotic')
            return
        for j in range(q[i]-2,i):
            if q[j]>q[i]:
                moves += 1
        
        
    print(moves-1)

if __name__ == '__main__':
    t = int(input())

    for t_itr in range(t):
        n = int(input())

        q = list(map(int, input().rstrip().split()))

        minimumBribes(q)
        
        
