#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the stepPerms function below.
def stepPerms(n):
    if n == 1:
        return 1
    if n == 2:
        return 2
    if n == 3:
        return 4
    # count = stepPerms(n-1)+stepPerms(n-2) + stepPerms(n-3)
    # return count if count <10000000007 else count %10000000007

    x1,x2,x3 = 1,2,4
    i = 4
    sum = x3
    while i <= n:
        sum += x1 + x2 
        x1 = x2
        x2 = x3
        x3 = sum
        i += 1
    return sum%10000000007

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = int(input())

    for s_itr in range(s):
        n = int(input())

        res = stepPerms(n)

        fptr.write(str(res) + '\n')

    fptr.close()
