#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the makeAnagram function below.
def makeAnagram(a, b):
    d1 = {}
    count = 0
    for c in a:
        d1[c] = d1.get(c,0)+1
    for c in b:
        if c in d1:
            d1[c] -= 1
            if d1[c] <= 0:
                del d1[c]
        else:
            count += 1
    count += sum(d1.values())
    return count 
        
    
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = input()

    b = input()

    res = makeAnagram(a, b)

    fptr.write(str(res) + '\n')

    fptr.close()
